version: "3.9"

services:
  app:
    build: .
    volumes:
      - .:/opt/code
    ports:
      - "5000:5000"
    environment:
      - FLASK_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://centralnicgroup:centralnicgroup@postgres/centralnicgroup
      - FLASK_SECRET_KEY=d90f9df0d56adc2b058b89585d5cb38306864b7e6988fb46
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres:14"
    environment:
      - PGDATA=/pgdata
      - POSTGRES_PASSWORD=password
    volumes:
      - centralnicgroup:/pgdata
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  centralnicgroup:
